@server_url = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6IkNsaWVudCIsImlhdCI6MTY3ODA2MjM2MCwiZXhwIjoxNjc4NjY3MTYwfQ.Yv5yPwPFigVNP8L_ztCq1sdi2KNAhe78a5z5N2Wjzt4

##======================================================================
## LOGIN
##======================================================================

### Login
POST {{server_url}}/auth/login HTTP/1.1
content-type: application/json

{
  "email": "luh@mail.com",
  "password": "@mah123"
}

### Logout
POST {{server_url}}/auth/logout HTTP/1.1
content-type: application/json

{}

##======================================================================
## USER
##======================================================================

### Get Users
GET {{server_url}}/user HTTP/1.1
Authorization: {{token}}

### Get User
GET {{server_url}}/user/2 HTTP/1.1
Authorization: {{token}}

### Create User
POST {{server_url}}/user HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
  "email": "mah@mail.com",
  "firstName": "Luiza",
  "lastName": "Alves",
  "password": "mah123",
  "role": "Admin"
}

### Update User
PUT {{server_url}}/user/2 HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
  "email": "mah@mail.com",
  "firstName": "Luiza",
  "lastName": "Alves da Silva",
  "password": "@mah123",
  "role": "Client"
}

### Delete User
DELETE {{server_url}}/user/1 HTTP/1.1
Authorization: {{token}}

##======================================================================
## City
##======================================================================

### Get Cities
GET {{server_url}}/city HTTP/1.1
Authorization: {{token}}

### Get City
GET {{server_url}}/city/1 HTTP/1.1
Authorization: {{token}}

### Create City
POST {{server_url}}/city HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
  "name": "Mongaguá",
  "latitude": -24.0892837,
  "longitude": -46.7086792,
  "regionId": 1
}

### Delete City
DELETE {{server_url}}/city/2 HTTP/1.1
Authorization: {{token}}

##======================================================================
## Cine
##======================================================================

### Get Cines
GET {{server_url}}/cine HTTP/1.1
Authorization: {{token}}

### Get Cine
GET {{server_url}}/cine/1 HTTP/1.1
Authorization: {{token}}

### Create Cine
POST {{server_url}}/cine HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
  "name": "Mais Cine",
  "logo": "logo.png",
  "cityId": 1
}